package com.loanmanagement.controller;

import com.loanmanagement.database.DatabaseConnection;
import com.loanmanagement.model.User;
import com.loanmanagement.navigation.NavigationManager;
import javafx.collections.FXCollections;
import javafx.concurrent.Task;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.stage.FileChooser;
import java.math.BigDecimal;
import java.sql.*;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.awt.Desktop;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** Displays a customer profile and lets an Admin maintain verified credit metadata. */
public class ProfileController {
    @FXML private TextField nameField, emailField, phoneField, incomeField, creditScoreField, scoreSourceField;
    @FXML private TextArea verificationNotesField;
    @FXML private TextArea addressField;
    @FXML private DatePicker reportDatePicker;
    @FXML private ComboBox<String> verificationStatusCombo;
    @FXML private Button uploadReportButton, openReportButton, saveReportReviewButton;
    @FXML private ComboBox<String> reportStatusCombo;
    @FXML private Label reportFileLabel, reportStatusLabel;
    @FXML private Label customerIdLabel, applicationsLabel, pendingLabel, approvedLabel, rejectedLabel, activeLoansLabel, closedLoansLabel, borrowedLabel, paidLabel, outstandingLabel, messageLabel;
    @FXML private ListView<String> activityList;
    private User currentUser; private int targetCustomerId, targetUserId; private ProfileData loadedProfile;

    @FXML public void initialize() { verificationStatusCombo.setItems(FXCollections.observableArrayList("NOT_VERIFIED", "PENDING_REVIEW", "VERIFIED")); reportStatusCombo.setItems(FXCollections.observableArrayList("PENDING_REVIEW", "VERIFIED", "REJECTED")); }
    public void setCurrentUser(User user) { currentUser=user; targetCustomerId=0; configureReportActions(); loadProfile(); }
    public void setCustomer(User viewer, int customerId) { currentUser=viewer; targetCustomerId=customerId; configureReportActions(); loadProfile(); }
    private void configureReportActions(){boolean customer=role("CUSTOMER"),admin=role("ADMIN");uploadReportButton.setVisible(customer);uploadReportButton.setManaged(customer);openReportButton.setVisible(false);openReportButton.setManaged(false);saveReportReviewButton.setVisible(false);saveReportReviewButton.setManaged(false);reportStatusCombo.setDisable(!admin);}

    private void loadProfile() {
        if (currentUser==null || (!role("CUSTOMER")&&!role("ADMIN"))) { showError("Access denied","Your account cannot open customer profiles."); return; }
        if (targetCustomerId==0&&!role("CUSTOMER")) { showError("Profile unavailable","Select a customer before opening a profile."); return; }
        Task<ProfileData> task=new Task<>() { protected ProfileData call() throws SQLException { return fetchProfile(); } };
        task.setOnSucceeded(e->{loadedProfile=task.getValue();render(task.getValue());loadLatestCreditReport();}); task.setOnFailed(e->showError("Profile unavailable","Unable to load the profile right now.")); start(task,"loanflow-profile-load");
    }

    private ProfileData fetchProfile() throws SQLException {
        try (Connection c=DatabaseConnection.getConnection()) {
            String sql="SELECT c.CUSTOMER_ID,c.USER_ID,u.FULL_NAME,u.EMAIL,c.PHONE,c.ADDRESS,NVL(cp.MONTHLY_INCOME,c.MONTHLY_INCOME),NVL(cp.ACADEMIC_CREDIT_SCORE,c.ACADEMIC_CREDIT_SCORE),NVL(cp.VERIFICATION_STATUS,'NOT_VERIFIED'),cp.SCORE_SOURCE,cp.REPORT_DATE,cp.VERIFICATION_NOTES,cp.VERIFIED_BY FROM LMS_CUSTOMER c JOIN USERS u ON u.USER_ID=c.USER_ID LEFT JOIN LOANFLOW_CREDIT_PROFILE cp ON cp.CUSTOMER_ID=c.CUSTOMER_ID WHERE "+(targetCustomerId>0?"c.CUSTOMER_ID=?":"c.USER_ID=?");
            int lookup=targetCustomerId>0?targetCustomerId:currentUser.getUserId(),cid,uid; String name,email,phone,address,status,source,notes; BigDecimal income; Integer score,verifiedBy; LocalDate reportDate;
            try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,lookup);try(ResultSet r=p.executeQuery()){if(!r.next())throw new SQLException("Profile not found");cid=r.getInt(1);uid=r.getInt(2);name=r.getString(3);email=r.getString(4);phone=r.getString(5);address=r.getString(6);income=r.getBigDecimal(7);int raw=r.getInt(8);score=r.wasNull()?null:raw;status=r.getString(9);source=r.getString(10);Date d=r.getDate(11);reportDate=d==null?null:d.toLocalDate();notes=r.getString(12);int rawVerifier=r.getInt(13);verifiedBy=r.wasNull()?null:rawVerifier;}}
            int apps=count(c,"SELECT COUNT(*) FROM LOAN_APPLICATION WHERE CUSTOMER_ID=?",cid),pending=count(c,"SELECT COUNT(*) FROM LOAN_APPLICATION WHERE CUSTOMER_ID=? AND UPPER(STATUS)='PENDING'",cid),approved=count(c,"SELECT COUNT(*) FROM LOAN_APPLICATION WHERE CUSTOMER_ID=? AND UPPER(STATUS)='APPROVED'",cid),rejected=count(c,"SELECT COUNT(*) FROM LOAN_APPLICATION WHERE CUSTOMER_ID=? AND UPPER(STATUS)='REJECTED'",cid),active=count(c,"SELECT COUNT(*) FROM LOAN WHERE CUSTOMER_ID=? AND STATUS='ACTIVE'",cid),closed=count(c,"SELECT COUNT(*) FROM LOAN WHERE CUSTOMER_ID=? AND STATUS='CLOSED'",cid);
            double borrowed=amount(c,"SELECT NVL(SUM(LOAN_AMOUNT),0) FROM LOAN WHERE CUSTOMER_ID=?",cid),paid=amount(c,"SELECT NVL(SUM(p.AMOUNT),0) FROM PAYMENT p JOIN LOAN l ON l.LOAN_ID=p.LOAN_ID WHERE l.CUSTOMER_ID=? AND p.PAYMENT_STATUS='PAID'",cid),repayable=amount(c,"SELECT NVL(SUM(EMI_AMOUNT*TENURE_MONTHS),0) FROM LOAN WHERE CUSTOMER_ID=?",cid);
            List<String> activity=new ArrayList<>(); String a="SELECT activity FROM (SELECT 'Application #'||APPLICATION_ID||' - '||STATUS activity_date,'Application #'||APPLICATION_ID||' - '||STATUS activity FROM LOAN_APPLICATION WHERE CUSTOMER_ID=? UNION ALL SELECT 'Payment #'||p.PAYMENT_ID||' - Loan #'||l.LOAN_ID activity_date,'Payment #'||p.PAYMENT_ID||' - Loan #'||l.LOAN_ID activity FROM PAYMENT p JOIN LOAN l ON l.LOAN_ID=p.LOAN_ID WHERE l.CUSTOMER_ID=?) ORDER BY activity_date DESC FETCH FIRST 8 ROWS ONLY";
            try(PreparedStatement p=c.prepareStatement(a)){p.setInt(1,cid);p.setInt(2,cid);try(ResultSet r=p.executeQuery()){while(r.next())activity.add(r.getString(1));}}
            return new ProfileData(cid,uid,name,email,phone,address,income,score,source,reportDate,status,notes,verifiedBy,apps,pending,approved,rejected,active,closed,borrowed,paid,Math.max(0,repayable-paid),activity);
        }
    }

    private void render(ProfileData d){targetCustomerId=d.cid;targetUserId=d.uid;customerIdLabel.setText(String.valueOf(d.cid));nameField.setText(empty(d.name));emailField.setText(empty(d.email));phoneField.setText(empty(d.phone));addressField.setText(empty(d.address));incomeField.setText(d.income==null?"":d.income.toPlainString());creditScoreField.setText(d.score==null?"":String.valueOf(d.score));scoreSourceField.setText(empty(d.source));reportDatePicker.setValue(d.reportDate);verificationStatusCombo.setValue(d.status==null?"NOT_VERIFIED":d.status);verificationNotesField.setText(empty(d.notes));boolean admin=role("ADMIN");creditScoreField.setDisable(!admin);scoreSourceField.setDisable(!admin);reportDatePicker.setDisable(!admin);verificationStatusCombo.setDisable(!admin);verificationNotesField.setDisable(!admin);applicationsLabel.setText(String.valueOf(d.apps));pendingLabel.setText(String.valueOf(d.pending));approvedLabel.setText(String.valueOf(d.approved));rejectedLabel.setText(String.valueOf(d.rejected));activeLoansLabel.setText(String.valueOf(d.active));closedLoansLabel.setText(String.valueOf(d.closed));borrowedLabel.setText(money(d.borrowed));paidLabel.setText(money(d.paid));outstandingLabel.setText(money(d.outstanding));activityList.setItems(FXCollections.observableArrayList(d.activity));}

    @FXML private void save(){String n=nameField.getText().trim(),e=emailField.getText().trim(),ph=phoneField.getText().trim(),ad=addressField.getText().trim();BigDecimal income;Integer score;try{income=incomeField.getText().trim().isEmpty()?null:new BigDecimal(incomeField.getText().trim());score=creditScoreField.getText().trim().isEmpty()?null:Integer.valueOf(creditScoreField.getText().trim());if(income!=null&&income.signum()<0||score!=null&&(score<300||score>900))throw new NumberFormatException();}catch(NumberFormatException ex){messageLabel.setText("Enter valid income and a score between 300 and 900.");return;}if(n.length()<3||!e.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")||(!ph.isEmpty()&&!ph.matches("[0-9+() -]{7,20}"))){messageLabel.setText("Enter a valid name, email, and phone number.");return;}boolean admin=role("ADMIN");String source=scoreSourceField.getText().trim(),status=verificationStatusCombo.getValue()==null?"NOT_VERIFIED":verificationStatusCombo.getValue();LocalDate reportDate=reportDatePicker.getValue();String notes=verificationNotesField.getText().trim();if(admin&&"VERIFIED".equals(status)&&(score==null||source.isEmpty()||reportDate==null)){messageLabel.setText("Verified status requires a score, source, and report date.");return;}
        Task<Boolean> task=new Task<>(){protected Boolean call() throws SQLException{try(Connection c=DatabaseConnection.getConnection()){c.setAutoCommit(false);try{try(PreparedStatement p=c.prepareStatement("UPDATE USERS SET FULL_NAME=?,EMAIL=? WHERE USER_ID=?")){p.setString(1,n);p.setString(2,e);p.setInt(3,targetUserId);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE LMS_CUSTOMER SET FULL_NAME=?,EMAIL=?,PHONE=?,ADDRESS=?,MONTHLY_INCOME=? WHERE USER_ID=?")){p.setString(1,n);p.setString(2,e);p.setString(3,ph.isEmpty()?null:ph);p.setString(4,ad.isEmpty()?null:ad);decimal(p,5,income);p.setInt(6,targetUserId);p.executeUpdate();}String m="MERGE INTO LOANFLOW_CREDIT_PROFILE t USING (SELECT CUSTOMER_ID FROM LMS_CUSTOMER WHERE USER_ID=?) s ON (t.CUSTOMER_ID=s.CUSTOMER_ID) WHEN MATCHED THEN UPDATE SET MONTHLY_INCOME=?,ACADEMIC_CREDIT_SCORE=?,CREDIT_HISTORY_STATUS=?,SCORE_SOURCE=?,REPORT_DATE=?,VERIFICATION_STATUS=?,VERIFICATION_NOTES=?,VERIFIED_BY=?,VERIFIED_AT=CASE WHEN ?='VERIFIED' THEN SYSDATE ELSE VERIFIED_AT END,UPDATED_AT=SYSDATE WHEN NOT MATCHED THEN INSERT (CUSTOMER_ID,MONTHLY_INCOME,ACADEMIC_CREDIT_SCORE,CREDIT_HISTORY_STATUS,SCORE_SOURCE,REPORT_DATE,VERIFICATION_STATUS,VERIFICATION_NOTES,VERIFIED_BY,VERIFIED_AT) VALUES (s.CUSTOMER_ID,?,?,?,?,?,?,?,?,CASE WHEN ?='VERIFIED' THEN SYSDATE ELSE NULL END)";try(PreparedStatement p=c.prepareStatement(m)){p.setInt(1,targetCustomerId);decimal(p,2,income);integer(p,3,score);p.setString(4,admin&&"VERIFIED".equals(status)?"Verified credit report":"Profile provided");p.setString(5,admin&&!source.isEmpty()?source:null);date(p,6,admin?reportDate:null);p.setString(7,admin?status:"NOT_VERIFIED");p.setString(8,admin?notes:null);if(admin&&"VERIFIED".equals(status))p.setInt(9,currentUser.getUserId());else p.setNull(9,Types.NUMERIC);p.setString(10,admin?status:"NOT_VERIFIED");decimal(p,11,income);integer(p,12,score);p.setString(13,admin&&"VERIFIED".equals(status)?"Verified credit report":"Profile provided");p.setString(14,admin&&!source.isEmpty()?source:null);date(p,15,admin?reportDate:null);p.setString(16,admin?status:"NOT_VERIFIED");p.setString(17,admin?notes:null);if(admin&&"VERIFIED".equals(status))p.setInt(18,currentUser.getUserId());else p.setNull(18,Types.NUMERIC);p.setString(19,admin?status:"NOT_VERIFIED");p.executeUpdate();}if(admin)try(PreparedStatement p=c.prepareStatement("INSERT INTO LOANFLOW_CREDIT_VERIFICATION_HISTORY (CUSTOMER_ID,CREDIT_SCORE,SCORE_SOURCE,REPORT_DATE,VERIFICATION_STATUS,VERIFICATION_NOTES,VERIFIED_BY) VALUES (?,?,?,?,?,?,?)")){p.setInt(1,targetCustomerId);integer(p,2,score);p.setString(3,source.isEmpty()?null:source);date(p,4,reportDate);p.setString(5,status);p.setString(6,notes.isEmpty()?null:notes);p.setInt(7,currentUser.getUserId());p.executeUpdate();}c.commit();return true;}catch(SQLException ex){c.rollback();throw ex;}}}};
        task.setOnSucceeded(x->{messageLabel.setText(admin?"Credit verification saved successfully.":"Profile updated successfully.");loadProfile();});task.setOnFailed(x->messageLabel.setText("Unable to save profile. Please run module7_credit_verification_migration.sql first."));start(task,"loanflow-profile-save");}

    private void loadLatestCreditReport(){Task<ReportData> task=new Task<>(){protected ReportData call() throws SQLException{try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT REPORT_ID,FILE_NAME,STORAGE_PATH,FILE_SIZE_BYTES,UPLOADED_AT,REPORT_STATUS,CREDIT_SCORE,NOTES FROM (SELECT REPORT_ID,FILE_NAME,STORAGE_PATH,FILE_SIZE_BYTES,UPLOADED_AT,REPORT_STATUS,CREDIT_SCORE,NOTES,ROW_NUMBER() OVER (ORDER BY UPLOADED_AT DESC,REPORT_ID DESC) RN FROM LOANFLOW_CREDIT_REPORT WHERE CUSTOMER_ID=?) WHERE RN=1")){p.setInt(1,targetCustomerId);try(ResultSet r=p.executeQuery()){if(!r.next())return null;int score=r.getInt(7);return new ReportData(r.getInt(1),r.getString(2),r.getString(3),r.getLong(4),r.getTimestamp(5),r.getString(6),r.wasNull()?null:score,r.getString(8));}}}};task.setOnSucceeded(e->{ReportData r=task.getValue();if(r==null){reportFileLabel.setText("No credit report uploaded.");reportStatusLabel.setText("No report submitted");openReportButton.setVisible(false);openReportButton.setManaged(false);saveReportReviewButton.setVisible(false);saveReportReviewButton.setManaged(false);return;}reportFileLabel.setText(r.fileName+" ("+r.fileSize+" bytes)");reportStatusLabel.setText("Status: "+r.status);reportStatusCombo.setValue(r.status);openReportButton.setVisible(role("ADMIN"));openReportButton.setManaged(role("ADMIN"));saveReportReviewButton.setVisible(role("ADMIN"));saveReportReviewButton.setManaged(role("ADMIN"));});task.setOnFailed(e->{reportFileLabel.setText("Credit report metadata unavailable.");reportStatusLabel.setText("Run module8_credit_report_upload_migration.sql");});start(task,"loanflow-credit-report-load");}
    @FXML private void uploadCreditReport(){if(!role("CUSTOMER")){showError("Access denied","Only the customer can upload their credit report.");return;}FileChooser chooser=new FileChooser();chooser.setTitle("Choose Credit Report PDF");chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("PDF files","*.pdf"));File selected=chooser.showOpenDialog(uploadReportButton.getScene().getWindow());if(selected==null)return;if(!selected.getName().toLowerCase(Locale.ROOT).endsWith(".pdf")||selected.length()>5*1024*1024){messageLabel.setText("Select a PDF credit report smaller than 5 MB.");return;}Task<Boolean> task=new Task<>(){protected Boolean call() throws Exception{Path folder=Paths.get("data","credit-reports",String.valueOf(targetCustomerId));Files.createDirectories(folder);String safe=selected.getName().replaceAll("[^A-Za-z0-9._-]","_");Path destination=folder.resolve(System.currentTimeMillis()+"_"+safe);Files.copy(selected.toPath(),destination);try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO LOANFLOW_CREDIT_REPORT (CUSTOMER_ID,FILE_NAME,STORAGE_PATH,FILE_SIZE_BYTES,REPORT_STATUS) VALUES (?,?,?,?,'PENDING_REVIEW')")){p.setInt(1,targetCustomerId);p.setString(2,selected.getName());p.setString(3,destination.toAbsolutePath().toString());p.setLong(4,selected.length());p.executeUpdate();}return true;}};task.setOnSucceeded(e->{messageLabel.setText("Credit report uploaded and is pending Admin review.");loadLatestCreditReport();});task.setOnFailed(e->messageLabel.setText("Credit report upload failed. Please try again."));start(task,"loanflow-credit-report-upload");}
    @FXML private void openCreditReport(){if(!role("ADMIN")){showError("Access denied","Only an Admin can open uploaded credit reports.");return;}loadReportPath(path->{if(path==null){showError("Report unavailable","No uploaded report is available.");return;}try{if(!Desktop.isDesktopSupported())throw new IllegalStateException();Desktop.getDesktop().open(new File(path));}catch(Exception e){showError("Report unavailable","The stored report file could not be opened.");}});}
    @FXML private void saveCreditReportReview(){if(!role("ADMIN")){showError("Access denied","Only an Admin can review credit reports.");return;}String status=reportStatusCombo.getValue();if(status==null){messageLabel.setText("Select a report status.");return;}Integer score=null;try{if(!creditScoreField.getText().trim().isEmpty())score=Integer.valueOf(creditScoreField.getText().trim());}catch(NumberFormatException e){messageLabel.setText("Enter a valid score between 300 and 900.");return;}if(score!=null&&(score<300||score>900)){messageLabel.setText("Enter a valid score between 300 and 900.");return;}final Integer finalScore=score;Task<Boolean> task=new Task<>(){protected Boolean call() throws SQLException{try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE LOANFLOW_CREDIT_REPORT SET REPORT_STATUS=?,CREDIT_SCORE=?,VERIFIED_BY=?,VERIFIED_AT=CASE WHEN ?='VERIFIED' THEN SYSDATE ELSE NULL END,NOTES=? WHERE REPORT_ID=(SELECT REPORT_ID FROM (SELECT REPORT_ID,ROW_NUMBER() OVER (ORDER BY UPLOADED_AT DESC,REPORT_ID DESC) RN FROM LOANFLOW_CREDIT_REPORT WHERE CUSTOMER_ID=?) WHERE RN=1)")){p.setString(1,status);integer(p,2,finalScore);p.setInt(3,currentUser.getUserId());p.setString(4,status);p.setString(5,verificationNotesField.getText().trim());p.setInt(6,targetCustomerId);p.executeUpdate();return true;}}};task.setOnSucceeded(e->{messageLabel.setText("Credit report review saved. Save changes to update the assessment profile.");loadLatestCreditReport();});task.setOnFailed(e->messageLabel.setText("Unable to save the credit report review."));start(task,"loanflow-credit-report-review");}
    private interface PathCallback{void accept(String path);}
    private void loadReportPath(PathCallback callback){Task<String> task=new Task<>(){protected String call() throws SQLException{try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT STORAGE_PATH FROM (SELECT STORAGE_PATH,ROW_NUMBER() OVER (ORDER BY UPLOADED_AT DESC,REPORT_ID DESC) RN FROM LOANFLOW_CREDIT_REPORT WHERE CUSTOMER_ID=?) WHERE RN=1")){p.setInt(1,targetCustomerId);try(ResultSet r=p.executeQuery()){return r.next()?r.getString(1):null;}}}};task.setOnSucceeded(e->callback.accept(task.getValue()));task.setOnFailed(e->callback.accept(null));start(task,"loanflow-credit-report-path");}
    private void decimal(PreparedStatement p,int i,BigDecimal v)throws SQLException{if(v==null)p.setNull(i,Types.NUMERIC);else p.setBigDecimal(i,v);}private void integer(PreparedStatement p,int i,Integer v)throws SQLException{if(v==null)p.setNull(i,Types.NUMERIC);else p.setInt(i,v);}private void date(PreparedStatement p,int i,LocalDate v)throws SQLException{if(v==null)p.setNull(i,Types.DATE);else p.setDate(i,Date.valueOf(v));}
    @FXML private void refresh(){loadProfile();}@FXML private void back(){try{String target=role("ADMIN")?"/fxml/admin.fxml":"/fxml/dashboard.fxml";NavigationManager.navigate((javafx.stage.Stage)nameField.getScene().getWindow(),target,"LoanFlow - Dashboard",c->{if(role("ADMIN"))((AdminController)c).setCurrentUser(currentUser);else ((DashboardController)c).setCurrentUser(currentUser);});}catch(Exception e){showError("Navigation error","Unable to return to the previous page.");}}
    private int count(Connection c,String s,int id)throws SQLException{try(PreparedStatement p=c.prepareStatement(s)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?r.getInt(1):0;}}}private double amount(Connection c,String s,int id)throws SQLException{try(PreparedStatement p=c.prepareStatement(s)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?r.getDouble(1):0;}}}private boolean role(String v){return currentUser!=null&&v.equalsIgnoreCase(currentUser.getRole());}private void start(Task<?> t,String n){Thread x=new Thread(t,n);x.setDaemon(true);x.start();}private String empty(String v){return v==null?"":v;}private String money(double v){return NumberFormat.getCurrencyInstance(new Locale("en","IN")).format(v);}private void showError(String t,String m){Alert a=new Alert(Alert.AlertType.ERROR);a.setTitle(t);a.setHeaderText(null);a.setContentText(m);a.showAndWait();}
    private static final class ReportData{final int id;final String fileName,path,status,notes;final long fileSize;final Timestamp uploadedAt;final Integer score;ReportData(int i,String f,String p,long z,Timestamp u,String s,Integer c,String n){id=i;fileName=f;path=p;fileSize=z;uploadedAt=u;status=s;score=c;notes=n;}}
    private static final class ProfileData{final int cid,uid,apps,pending,approved,rejected,active,closed;final String name,email,phone,address,source,status,notes;final BigDecimal income;final Integer score,verifiedBy;final LocalDate reportDate;final double borrowed,paid,outstanding;final List<String> activity;ProfileData(int c,int u,String n,String e,String p,String a,BigDecimal i,Integer s,String so,LocalDate rd,String st,String no,Integer vb,int ap,int pe,int ok,int re,int ac,int cl,double b,double pa,double o,List<String> l){cid=c;uid=u;name=n;email=e;phone=p;address=a;income=i;score=s;source=so;reportDate=rd;status=st;notes=no;verifiedBy=vb;apps=ap;pending=pe;approved=ok;rejected=re;active=ac;closed=cl;borrowed=b;paid=pa;outstanding=o;activity=l;}}
}
